### ISSUE TITLE
last row of MQB gets assigned incorrect DQB

### ISSUE THREAD

**Issue by Gaphodil** [alexnguyenn/surface-code-generator#2]
relevant code is in `circuit_new.py -> generate_lattice()`
look at [this section](https://github.com/alexnguyenn/surface-code-generator/blob/652c4457add53c154f348888ec0454a3ea70724a/circuit_new.py#L62) and compare with [this one](https://github.com/alexnguyenn/surface-code-generator/blob/652c4457add53c154f348888ec0454a3ea70724a/circuit_new.py#L35)

**Comment by alexnguyenn** [comment]
Was a typo, fixed in 4e41efb67ffecddc1895534f7f5a0d3f87c84dc8
